### ISSUE TITLE
Drill down feature for bar, pie, or donut chart

### ISSUE THREAD

**Issue by w3o-io** [Glavin001/ember-c3#76]
Is there a way to do drill-down with ember-c3 component?

**Comment by maxwondercorn** [comment]
Not easily because the C3 chart methods are not exposed for data loading/unloading. I've been working (slowly) at upgrading the add-on.  Exposing the methods and events has been completed in a fork and you can see an example of how to do drill down in the fork [here](https://github.com/maxwondercorn/ember-c3/blob/master/tests/dummy/app/controllers/drilldown.js)

I'm cleaning up the demo application and readme to document the changes before merging.

**Comment by maxwondercorn** [comment]
See issue #77

**Comment by maxwondercorn** [comment]
Added access to to c3 api in pr #79.  See drill down demo after update is published
